export enum Status {
    IN_PROGRESS = 'IN_PROGRESS',
    PAID_INCOMPLETE = 'PAID_INCOMPLETE',
    PAID_COMPLETE = 'PAID_COMPLETE',
    UNPAID_COMPLETE = 'UNPAID_COMPLETE',
    UNPAID_INCOMPLETE = 'UNPAID_INCOMPLETE',
    ORDER_SUBMITTED = 'ORDER_SUBMITTED',
    PROCESSING = "PROCESSING",
    SHIPPED = 'SHIPPED',
    DELIVERED = "DELIVERED",
    CANCELED = "CANCELED",
    ERROR = 'ERROR'
}


export enum EmailStatus {
    ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
    ORDER_PROCESSING = 'ORDER_PROCESSING',
    ORDER_DELIVERED = 'ORDER_DELIVERED'
}